name: flodash
description: A dart implementation of the popular JavaScript library Lodash
version: 1.1.0-blizzard.4
repository: https://github.com/sliit-foss/flodash

environment:
  sdk: ">=2.12.0 <3.7.0"

dev_dependencies:
  flutter_test:
    sdk: flutter