name: enhanced_http
description: A wrapper around the dart http package provided by Google which is inspired by axios
version: 4.2.4
repository: https://github.com/sliit-foss/dart-cookbook/tree/main/packages/enhanced_http

environment:
  sdk: ">=2.12.0 <=3.7.2"

dependencies:
  http: ^1.0.0
  http_parser: ^4.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter